sudo: required
dist: trusty

language: php
php:
  - 7.1.3

before_install:
  - sudo rm -rf ~/.nvm - curl -sL "https://deb.nodesource.com/setup_8" | sudo -E bash -
  - sudo apt-get install -y nodejs

install:
  - composer install
  - npm install

script:
  - npm test

env:
  global:
    secure: G3kMcQl11oBl4fAuOqmPDcCfgxmeYFEMxgXhcIlHVQOijPkuWy6Q4SCef3xJSVRt6SPNoq0x7dCZzLWlyCWLADPV4I/i96BcWOKn7mOuDPzYFnb+tuyz8dHZhG2Ku7OeEAXmJBWybT6Q+v69+d8xUwCB6FEdZHfC6pco7wLIFPD2kzGS45D11HvFjXl6WtUCp/t7i5/WuF8FNq0SOkdSBj4bUXcyB1zS/EtbDiS27n8KWNsxdh9FTAV7vulANctogq6gp5+xlXZLoxl+gUWZom2II6lyVofLpQ25neoFUSoKdJYJdNEyvBrdU5YUYQ+Lqq28KrUeJvisjWS2GFj0T21zhI85PxO88QkP9P15WzNnPdT+Bqr9njCicXAymZ9v+SJby0PRiW/nYE0qHpeldY7y5RS1T/DrhkQESLUPjQl5fJ2Hk1lrfR3q3x3xZLm4GpyfFuDoXBhCGzfedaV7bAWjQoanyaRWHvPNPGxV6Zmk8kzW8q8xTLKNA54r1h1P2gRmATtdBd7nU4j9LcQKkynJEkcmZWkfYjMxFkMgkEM7etw6DFpzcNKDvrup5K3VI8c1lP7zemgwhC3pKyjExLVdJGl8PvtxG9PAk67fF8X8F0RWGg6Zte+x88E49EryHf+tV/Hc9JAdXSeaSXR830b5mEArPXYtwwrB/jgPFNI=